import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './containers/Header'
import { Nav } from './containers/Nav'
import { Footer } from './containers/Footer'
import { Network } from './containers/Network'
import { configSite } from './service/configSite'
// import { Ads } from './containers/Ads'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const site = await configSite();
  const data = site.response.data[0];
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header data={data} />
        <Nav />
        {children}
        <Footer data={data} />
        <Network />
        {/* <Ads /> */}
      </body>
    </html>
  )
}
